apiVersion: v1
kind: Service
metadata:
    name: "aasapk8scluster-1137"
    labels:
        app: "aasapk8scluster-1137"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aasapk8scluster-1137"