on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aasapdockerregistry.azurecr.io
        username: ${{ secrets.acr_aasapdockerregistry_username }}
        password: ${{ secrets.acr_aasapdockerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aasapdockerregistry.azurecr.io/aasapk8scluster:${{ github.sha }}
        docker push aasapdockerregistry.azurecr.io/aasapk8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aasapk8scluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aasap-dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aasap-dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aasap-dev
        container-registry-url: aasapdockerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_aasapdockerregistry_username }}
        container-registry-password: ${{ secrets.acr_aasapdockerregistry_password }}
        secret-name: aasapk8sclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aasap-dev
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          aasapdockerregistry.azurecr.io/aasapk8scluster:${{ github.sha }}
        imagepullsecrets: |
          aasapk8sclusdockerauth